In [21]:
import pandas as pd
from datetime import datetime
import os

In [8]:
# Import csv 
charting_songs = pd.read_csv('christmas_billboard_data.csv')

# Information of the data
charting_songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387 entries, 0 to 386
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   url                     387 non-null    object
 1   weekid                  387 non-null    object
 2   week_position           387 non-null    int64
 3   song                    387 non-null    object
 4   performer               387 non-null    object
 5   songid                  387 non-null    object
 6   instance                387 non-null    int64
 7   previous_week_position  279 non-null    float64
 8   peak_position           387 non-null    int64
 9   weeks_on_chart          387 non-null    int64
 10  year                    387 non-null    int64
 11  month                   387 non-null    int64
 12  day                     387 non-null    int64
dtypes: float64(1), int64(7), object(5)
memory usage: 39.4+ KB

In [5]:
charting_songs.describe()

,week_position,instance,previous_week_position,peak_position,weeks_on_chart,year,month,day
count,387.000000,387.000000,279.000000,387.000000,387.000000,387.000000,387.000000,387.000000
mean,57.204134,1.586563,55.519713,37.534884,9.645995,1982.064599,7.754522,16.671835
std,25.398527,1.250751,25.147310,24.760630,6.142627,21.118797,5.325586,8.904113
min,7.000000,1.000000,7.000000,7.000000,1.000000,1958.000000,1.000000,1.000000
25%,38.500000,1.000000,35.000000,14.000000,5.000000,1962.000000,1.000000,9.000000
50%,58.000000,1.000000,57.000000,34.000000,8.000000,1975.000000,12.000000,17.000000
75%,78.000000,1.000000,75.000000,53.500000,15.000000,2005.000000,12.000000,24.000000
max,100.000000,6.000000,100.000000,100.000000,20.000000,2017.000000,12.000000,31.000000

In [9]:
charting_songs

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,month,day
0,http://www.billboard.com/charts/hot-100/1958-1...,12/13/1958,83,RUN RUDOLPH RUN,Chuck Berry,Run Rudolph RunChuck Berry,1,NaN,69,3,1958,12,13
1,http://www.billboard.com/charts/hot-100/1958-1...,12/20/1958,57,JINGLE BELL ROCK,Bobby Helms,Jingle Bell RockBobby Helms,1,NaN,29,19,1958,12,20
2,http://www.billboard.com/charts/hot-100/1958-1...,12/20/1958,73,RUN RUDOLPH RUN,Chuck Berry,Run Rudolph RunChuck Berry,1,83.0,69,3,1958,12,20
3,http://www.billboard.com/charts/hot-100/1958-1...,12/20/1958,86,WHITE CHRISTMAS,Bing Crosby,White ChristmasBing Crosby,1,NaN,12,13,1958,12,20
4,http://www.billboard.com/charts/hot-100/1958-1...,12/27/1958,44,GREEN CHRI$TMA$,Stan Freberg,Green Chri$tma$Stan Freberg,1,NaN,44,2,1958,12,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,http://www.billboard.com/charts/hot-100/2017-0...,1/7/2017,16,ALL I WANT FOR CHRISTMAS IS YOU,Mariah Carey,All I Want For Christmas Is YouMariah Carey,6,20.0,11,19,2017,1,7
383,http://www.billboard.com/charts/hot-100/2017-0...,1/7/2017,27,ROCKIN' AROUND THE CHRISTMAS TREE,Brenda Lee,Rockin' Around The Christmas TreeBrenda Lee,6,48.0,14,18,2017,1,7
384,http://www.billboard.com/charts/hot-100/2017-0...,1/7/2017,48,IT'S THE MOST WONDERFUL TIME OF THE YEAR,Andy Williams,It's The Most Wonderful Time Of The YearAndy W...,1,NaN,48,1,2017,1,7
385,http://www.billboard.com/charts/hot-100/2017-0...,1/14/2017,35,ALL I WANT FOR CHRISTMAS IS YOU,Mariah Carey,All I Want For Christmas Is YouMariah Carey,6,16.0,11,19,2017,1,14
386,http://www.billboard.com/charts/hot-100/2017-0...,1/14/2017,41,LAST CHRISTMAS,Wham!,Last ChristmasWham!,1,50.0,41,2,2017,1,14

After reviewing the data:

 - Drop columns 'url' , 'weekid'
 - need to determine what the column 'instance' means
 - In the field 'previous_week_position' , I will input the position 101 for nulls. Reasoning is the song was not in the top 100 songs list at the time. Consider the integer 101 to be the 'zero' for the data set for the field.
 - convert fields month day year into data time format

In [15]:
# Make copy of original dataframe
charting_songs_copy = charting_songs.copy(deep=True)

In [16]:
# Create variable to drop from dataframe, then execute removal
columns = ['url', 'weekid']
charting_songs_copy.drop(columns, axis=1, inplace=True)

In [20]:
# Imput nulls with the integer 101.  101 will represent not being in the top 100 list the previous week before
charting_songs_copy['previous_week_position'] = charting_songs_copy['previous_week_position'].fillna(101)

## Convert to date objects

df['new_date'] = pd.to_datetime(df['old_date'].astype(str), format='%Y%m%d')

In [32]:
charting_songs_copy['year'] = pd.to_datetime(charting_songs_copy['year'].astype(str).str.strip(), format="%Y-%m-%d").dt.strftime( "%Y")

In [27]:
charting_songs_copy['year'] = pd.to_datetime(charting_songs_copy['year'].astype(str).str.strip(), format='%Y')

ValueError: unconverted data remains: -01-01

In [25]:
charting_songs_copy['month'] = pd.to_datetime(charting_songs_copy['month'].astype(str), format='%m')

In [26]:
charting_songs_copy['day'] = pd.to_datetime(charting_songs_copy['day'].astype(str), format='%d')

In [33]:
charting_songs_copy

,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart,year,month,day
0,83,RUN RUDOLPH RUN,Chuck Berry,Run Rudolph RunChuck Berry,1,101.0,69,3,1958,1900-12-01,1900-01-13
1,57,JINGLE BELL ROCK,Bobby Helms,Jingle Bell RockBobby Helms,1,101.0,29,19,1958,1900-12-01,1900-01-20
2,73,RUN RUDOLPH RUN,Chuck Berry,Run Rudolph RunChuck Berry,1,83.0,69,3,1958,1900-12-01,1900-01-20
3,86,WHITE CHRISTMAS,Bing Crosby,White ChristmasBing Crosby,1,101.0,12,13,1958,1900-12-01,1900-01-20
4,44,GREEN CHRI$TMA$,Stan Freberg,Green Chri$tma$Stan Freberg,1,101.0,44,2,1958,1900-12-01,1900-01-27
...,...,...,...,...,...,...,...,...,...,...,...
382,16,ALL I WANT FOR CHRISTMAS IS YOU,Mariah Carey,All I Want For Christmas Is YouMariah Carey,6,20.0,11,19,2017,1900-01-01,1900-01-07
383,27,ROCKIN' AROUND THE CHRISTMAS TREE,Brenda Lee,Rockin' Around The Christmas TreeBrenda Lee,6,48.0,14,18,2017,1900-01-01,1900-01-07
384,48,IT'S THE MOST WONDERFUL TIME OF THE YEAR,Andy Williams,It's The Most Wonderful Time Of The YearAndy W...,1,101.0,48,1,2017,1900-01-01,1900-01-07
385,35,ALL I WANT FOR CHRISTMAS IS YOU,Mariah Carey,All I Want For Christmas Is YouMariah Carey,6,16.0,11,19,2017,1900-01-01,1900-01-14
386,41,LAST CHRISTMAS,Wham!,Last ChristmasWham!,1,50.0,41,2,2017,1900-01-01,1900-01-14

In [34]:
charting_songs_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387 entries, 0 to 386
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   week_position           387 non-null    int64
 1   song                    387 non-null    object
 2   performer               387 non-null    object
 3   songid                  387 non-null    object
 4   instance                387 non-null    int64
 5   previous_week_position  387 non-null    float64
 6   peak_position           387 non-null    int64
 7   weeks_on_chart          387 non-null    int64
 8   year                    387 non-null    object
 9   month                   387 non-null    datetime64[ns]
 10  day                     387 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(4), object(4)
memory usage: 33.4+ KB

In [28]:
charting_songs_copy.year.value_counts()

1962-01-01    39
1960-01-01    33
1961-01-01    31
2011-01-01    16
1964-01-01    14
1959-01-01    13
2016-01-01    13
1974-01-01    13
2006-01-01    12
2005-01-01    11
2000-01-01    11
2007-01-01    11
2017-01-01    10
1981-01-01    10
2014-01-01    10
1963-01-01    10
1975-01-01     9
1989-01-01     8
1958-01-01     8
1980-01-01     7
1969-01-01     7
1973-01-01     7
1985-01-01     6
2015-01-01     6
2013-01-01     6
1965-01-01     5
1970-01-01     5
1998-01-01     5
1984-01-01     4
2012-01-01     4
2010-01-01     4
1990-01-01     4
1994-01-01     4
1978-01-01     4
1979-01-01     4
1997-01-01     3
1968-01-01     3
1993-01-01     3
1976-01-01     2
1999-01-01     2
1996-01-01     2
2009-01-01     2
1966-01-01     2
2001-01-01     2
2008-01-01     1
1995-01-01     1
Name: year, dtype: int64